user_management/user_management/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from users_app import views
from django.conf.urls.static import static

# YOU HAVE TO ADD THE 'STATIC' FUNCTION IN ORDER TO VIEW THE FILES IN THE MEDIA DIRECTORY!

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index , name='index' ),
    path('users_app/', include(('users_app.urls','users_app'),namespace='registrations')),
    path('', include(('users_app.urls','users_app'),namespace='index')),
    path('users_app/user_login/', views.success,name='success'),
    path('loggedout', views.user_logout, name='logout'),
    path('templates/users_app/',include(('users_app.urls','users_app'),namespace='login')),
]   + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user_management/users_app/urls.py
from django.urls import path,include
from users_app import views

# template urls!

app_name    =   'users_app'

urlpatterns=[
    path('',views.index, name='index'),
    path('registration.html', views.register , name='register'),
    path('index.html', views.index , name='home'),
    path('login.html', views.user_login, name='user_login'),
]

user_management/users_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserInfo(models.Model):

    
    user    =   models.OneToOneField(User,on_delete=models.CASCADE)

    # additional user attributes
    portfolio   =   models.URLField(blank=True)
    propic      =   models.ImageField(upload_to='propics',blank=True)

    def __str__(self):
        return self.user.username

user_management/users_app/forms.py
from django import forms
from django.contrib.auth.models import User
from users_app.models import UserInfo

class UserForm(forms.ModelForm):
    password    =   forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model  =   User
        fields  =   ('username','email','password')

class UserInfoForm(forms.ModelForm):
    class Meta():
        model   =   UserInfo
        fields  =   ('portfolio','propic')

user_management/users_app/views.py
from django.shortcuts import render
from users_app.forms import UserForm,UserInfoForm
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout


def index(request):

    return render(request,'users_app/index.html')

def register(request):

    registered = False

    if request.method == 'POST':

        user1 = UserForm(data=request.POST)
        profile1 = UserInfoForm(data=request.POST)

        if user1.is_valid() and profile1.is_valid():

            user   =   user1.save()
            user.set_password(user.password)
            user.save()

            profile    =   profile1.save(commit=False)
            profile.user   =   user

            if 'propic' in request.FILES:
                profile.propic = request.FILES['propic']

            profile.save()

            registered = True

        else:
            print(user1.errors,profile1.errors)
    else:
        user1    =   UserForm()
        profile1 =   UserInfoForm()

    return render(request,'users_app/registration.html',{'user1':user1,'profile1':profile1,'registration':register})

def user_login(request):

    if request.method == 'POST':

        username    =   request.POST.get('username')
        password    =   request.POST.get('password')

        # django automated authentiacation!
        user    =   authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not ACTIVE!")
        else:
            print('Someone tried to login and failed XOXO!')
            print(f'Username:{username}/n Password:{password}')

    else:
        return render(request,'users_app/login.html',{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def success(request):
    return render(request,'users_app/success.html')












# Create your views here.

user_management/templates/users_app/index.html
{% extends 'users_app/parent.html' %}

{% block content_block %}
<div class="jumbotron">
  <h1>django level 5</h1>
</div>
{% endblock %}

user_management/templates/users_app/login.html
{% extends 'users_app/parent.html' %}
{% block content_block %}

<div class="jumbotron">
  <h1>Please Login!</h1>
  <form action="{% url 'login:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Name here">
    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="Pass">

    <input  type="submit" formmethod="POST" name="" value="login">

  </form>

</div>
{% endblock %}

user_management/templates/users_app/parent.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <title></title>
  </head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index:home' %}">django<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'registrations:register' %}">Register</a>
      </li>
      {% if user.is_authenticated %}
      <li> <a class="nav-link" href="{% url 'logout' %}">Logout</a> </li>
      {% else %}
      <li> <a class="nav-link" href="{% url 'login:user_login' %}">Login</a> </li>
      {% endif %}
    </ul>
  </nav>

  </div>
  <div class="container">
    {% block content_block %}
    {% endblock %}

  </div>


  </body>
</html>

user_management/templates/users_app/registration.html
{% extends 'users_app/parent.html' %}
{% load static %}

{% block content_block %}
<div class="jumbotron">
  {% if registered %}
  <h1>Thanks for Registering!</h1>
  {% else %}
  <h1>Register Here</h1>
  <h2>Fill out the form</h2>
  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ user1.as_p }}
    {{ profile1.as_p }}
    <!-- without the formmethod attribute, the method in the opening tag will always get overridden! -->
    <input type="submit" formmethod="POST" name="" value="Register">

  </form>
  {% endif %}

</div>
{% endblock %}

user_management/templates/users_app/success.html
{% extends 'users_app/parent.html' %}
{% block content_block %}

<div class="container">
  <div class="jumbotron">
    <h1>You logged in! N I C E !</h1>
    <h2><a href="{% url 'index' %}">Click me to go to homepage :)</a></h2>

  </div>

</div>
{% endblock %}